### ISSUE TITLE
Vor'Ral Support Battlecruiser name mismatch

### ISSUE THREAD

**Issue by izenn** [laurinius/sto-aso#17]
Admiralty Card Screenshot: (Drag and drop image here)
<img width="332" alt="image" src="https://user-images.githubusercontent.com/744288/196467065-f9fdc131-4ff3-499e-b3c2-6c67e0aa8d26.png">

aso screenshot:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/744288/196469177-bb6358e7-ad44-4c02-8039-c81ad54d72b7.png">

**Comment by laurinius** [comment]
Data files updated. No new software release, can be updated via "Update Data".
