### ISSUE TITLE
mirror engle strike wing escort name mismatch

### ISSUE THREAD

**Issue by izenn** [laurinius/sto-aso#18]
Admiralty Card Screenshot: (Drag and drop image here)
<img width="336" alt="image" src="https://user-images.githubusercontent.com/744288/196471119-811a537c-70b7-428b-a6c5-d42b0b7eb562.png">

aso card screenshot
<img width="357" alt="image" src="https://user-images.githubusercontent.com/744288/196471212-d97d9036-70ab-4af7-8ad9-85603a59fde7.png">

**Comment by laurinius** [comment]
Data files updated. No new software release, can be updated via "Update Data".
