### ISSUE TITLE
Vo'Devwl Support Carrier

### ISSUE THREAD

**Issue by izenn** [laurinius/sto-aso#2]
Admiralty Card Screenshot: (Drag and drop image here)
<img width="347" alt="image" src="https://user-images.githubusercontent.com/744288/194894504-f14fe6c0-cc98-4c7c-8e83-5ca150c12a1b.png">

Ship Name: Vo'Devwl Support Carrier
Ship Type: SCI
Rarity: Rare
Tier: T6
ENG: 26
SCI: 55
TAC: 26
Ability: -25% maintenance per SciShip

**Comment by laurinius** [comment]
Coming in 1.1.2
