### ISSUE TITLE
U.S.S. Voyager

### ISSUE THREAD

**Issue by zandif** [laurinius/sto-aso#20]
Admiralty Card Screenshot: (Drag and drop image here)
![image](https://user-images.githubusercontent.com/2258651/197803967-5ad89f65-d5b7-4f32-9e05-f82f76185276.png)

Ship Name: U.S.S. Voyager
Ship Type: SCI 
Rarity: Epic
Tier: T6
ENG: 41
SCI: 22
TAC: 72
Ability: -25% Maintenance per ANY Ship (Not Small Craft)

Link: [U.S.S. Voyager Admiralty Card](https://sto.fandom.com/wiki/Admiralty_System/Special_Admiralty_Ships#U.S.S._Voyager)

**Comment by laurinius** [comment]
Data files updated. No new software release needed. Can be updated via "Update Data".
