### ISSUE TITLE
Bozeman Intel Heavy Frigate

### ISSUE THREAD

**Issue by izenn** [laurinius/sto-aso#3]
Admiralty Card Screenshot: (Drag and drop image here)
<img width="354" alt="image" src="https://user-images.githubusercontent.com/744288/194900450-6df8d2d1-3868-4532-9293-2e93f969419e.png">

Ship Name: Bozeman Intel Heavy Frigate
Ship Type: ENG
Rarity: Rare
Tier: T6
ENG: 48
SCI: 22
TAC: 38
Ability: 2.5x Critical Rating from ENG

**Comment by laurinius** [comment]
Coming in 1.1.2
