### ISSUE TITLE
Vor'ral Support Battlecruiser

### ISSUE THREAD

**Issue by izenn** [laurinius/sto-aso#4]
Admiralty Card Screenshot: (Drag and drop image here)
<img width="341" alt="image" src="https://user-images.githubusercontent.com/744288/194901003-689b827d-7819-40a3-9ba6-252be9f669c9.png">

Ship Name: Vor'ral Support Battlecruiser
Ship Type: ENG
Rarity: Rare
Tier: T6
ENG: 62
SCI: 19
TAC: 27
Ability: -25% Maintenance per EngShip

**Comment by laurinius** [comment]
Coming in 1.1.2
