### ISSUE TITLE
Pilot Destroyer

### ISSUE THREAD

**Issue by izenn** [laurinius/sto-aso#5]
Admiralty Card Screenshot: (Drag and drop image here)
<img width="350" alt="image" src="https://user-images.githubusercontent.com/744288/194901484-0e3eb95e-b157-4719-8d38-98b25016aa3e.png">

Ship Name: Pilot Destroyer
Ship Type: TAC
Rarity: Rare
Tier: T6
ENG: 41
SCI: 20
TAC: 65
Ability: +10 TAC per TacShip

**Comment by laurinius** [comment]
Coming in 1.1.2
