### ISSUE TITLE
Terran Cygnus Battlecruiser

### ISSUE THREAD

**Issue by izenn** [laurinius/sto-aso#6]
Admiralty Card Screenshot: (Drag and drop image here)
<img width="345" alt="image" src="https://user-images.githubusercontent.com/744288/194901991-186bf4d4-8c06-4f0e-8c67-cf0dff13e456.png">

Ship Name: Terran Cygnus Battlecruiser
Ship Type: ENG
Rarity: Very Rare
Tier: T6
ENG: 48
SCI: 29
TAC: 40
Ability: +20 SCI and TAC when Alone

**Comment by laurinius** [comment]
Coming in 1.1.2
